[workspace]
resolver = "2"
members = ["fixture", "fixture_derive"]

[workspace.package]
description = "Fixture derive macro for Type Driven Development"
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["ProbablyClem"]
version = "0.0.1"
edition = "2024"
keywords = ["fixture", "test", "macro", "type-driven-development"]
